version: "3.8"

services:
  postgres:
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=mydatabase"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=myuser"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  evento-app:
    build:
      context: ./evento-backend/app
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase"
      - "SPRING_DATASOURCE_USERNAME=myuser"
      - "SPRING_DATASOURCE_PASSWORD=secret"
      - "SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"

  evento-frontend:
    build:
      context: ./evento-frontend
    ports:
      - "4440:80"
    depends_on:
      - evento-app
