spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres
  data:
    redis:
      host: localhost
      port: 6379
security:
  jwt:
    secret-key: 0adb62ddec61f0d5b99cbede06a95e41de6a209a6d37fcd4346903aa455ae4a8
    expiration-time: 3600000 # 1 hour, time is in milliseconds
  cors:
    allowed-domains: "*" # Allow all domains
management:
  endpoints:
    web:
      exposure:
        include: "*"
